openapi: 3.0.3
info:
  title: API de Ejemplo
  description: "Esta es una API de ejemplo para demostrar la especificación OpenAPI."
  version: 1.0.0
servers:
  - url: 'http://localhost:8080/'
paths:
  /usuarios:
    get:
      summary: Obtiene una lista de usuarios
      responses:
        '200':
          description: Lista de usuarios
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserModel'
components:
  schemas:
    Usuario:
      type: object
      properties:
        id:
          type: integer
          format: int64
        nombre:
          type: string
        email:
          type: string
          format: email
